### ISSUE TITLE
simple-expand is opening more than one target at the same time

### ISSUE THREAD

**Issue by grateful** [sylvain-hamel/simple-expand#1]
Hi, I am trying out your plugin - the way it fits into the code so simply is a big attraction for me. 

I am creating typical sidebar navigation for archive blog entries and would like each year listed to hide/show all the entries for that year. The code generated is as follows for each year:

<a class="expander toggle" href="... link to archive year">2012</a> 

<div class="content">
<ul>
    <li> ... link to archived item </li>
    <li> ... link to archived item </li>
    <li> ... link to archived item </li>
    <li> ... link to archived item </li>
</ul>
</div>

But where I have more than one year (i.e. the code above is repeated) all the targets open together rather than independently. 

Apologies if your documentation covers this, but to a javascript beginner it is't obvious what I need to do.

Many thanks for sharing this code!

**Comment by sylvain-hamel** [comment]
If you use the defaults, make sure you enclose each pair of container/target in an element.

instead of

```
<a class="expander" href="#">2012</a>
<ul class="content">
</ul>

<a class="expander" href="#">2011</a>
<ul class="content">
</ul>
```

use:

```
<div>
    <a class="expander" href="#">2012</a>
    <ul class="content">
    </ul>
</div>
<div>
    <a class="expander" href="#">2011</a>
    <ul class="content">
        content to hide.
    </ul>
</div>
```

**Comment by grateful** [comment]
Great, thanks - works brilliantly.

**Comment by ghost** [comment]
Hi, I have this issue.
I added divs however a display:none; keeps getting placed automatically out of nowhere on to the item which needs to be clicked.
Any advice would be appreciated, thanks

**Comment by sylvain-hamel** [comment]
@karam94 if you send me a repro project (on http://plnkr.co/ maybe) I'll investigate.
