### ISSUE TITLE
Persistence

### ISSUE THREAD

**Issue by grateful** [sylvain-hamel/simple-expand#2]
Since I am setting up a blog style navigation menu I need to allow the open states to persist across pages. Is this something that is easy to implement in the script?

**Comment by sylvain-hamel** [comment]
I implemented the keepStateInCookie option (313dbc740b723412924ad43b3f13d51d74e6ea0f)

```
$('.expander').simpleexpand({keepStateInCookie:true});
```
- Make sure you load the jQuery cookie plug-in (https://github.com/carhartl/jquery-cookie/) before simple-expand.js. 
- Make sure each expander has an Id attribute. 
- See /demo/demo_cookie.html in the repo.

**Comment by grateful** [comment]
Many thanks!

----- Original Message ----- 
From: "RedHotSly" 
reply@reply.github.com
To: "grateful" mail@aoart.co.uk
Sent: Sunday, August 05, 2012 11:34 PM
Subject: Re: [simple-expand] Persistence (#2)

**Comment by sylvain-hamel** [comment]
@grateful : can this issue be closed now?
