### ISSUE TITLE
programmatically close the container

### ISSUE THREAD

**Issue by pcout** [sylvain-hamel/simple-expand#8]
Hello,

How can i programmatically close the container ?
I am thinking of a callback using jquery that after an ajax call it closes the container programmatically .

Thanks

**Comment by sylvain-hamel** [comment]
Hi, you can simply call `$("#your-expander-id").click()` to close it. You can check whether or not the expander is currently expended by checking if it has the `expanded` css class set.

**Comment by sylvain-hamel** [comment]
@pcout : did it work? can you close the issue if it did. Thanks

**Comment by sylvain-hamel** [comment]
closing issue after too long without a response
